import eslint from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";
import prettierPlugin from "eslint-plugin-prettier";

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "*.config.*",
      // Generated by scripts/build-wasm.mjs — see src/zstd-wasm/.
      // The base64 wasm string and wasm-bindgen JS glue aren't
      // hand-written and shouldn't be linted.
      "src/zstd-wasm/wasm-bytes.ts",
      "src/zstd-wasm/ctopo_zstd_decoder.js",
      "src/zstd-wasm/ctopo_zstd_decoder.d.ts",
    ],
  },
  {
    files: ["src/**/*.ts"],
    extends: [
      eslint.configs.recommended,
      ...tseslint.configs.recommendedTypeChecked,
      prettier,
    ],
    languageOptions: {
      parserOptions: {
        project: "./tsconfig.lint.json",
      },
    },
    plugins: { prettier: prettierPlugin },
    rules: {
      "no-console": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "prettier/prettier": "error",
    },
  },
);
