#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
// © 2026 Michael Maurizi Jr.
//
// Build the zstd-decoder Rust crate to wasm and wire its output
// into src/zstd-wasm/. Run via `npm run build:wasm`. Output files
// are checked in so `npm install` doesn't need a Rust toolchain.
//
// Steps:
//   1. wasm-pack build --release --target web (skips its bundled
//      wasm-opt — see Cargo.toml metadata; that copy of wasm-opt
//      pre-dates --enable-bulk-memory).
//   2. wasm-opt -Oz with bulk-memory enabled.
//   3. Copy the generated JS + .d.ts into src/zstd-wasm/.
//   4. Base64-encode the wasm and emit src/zstd-wasm/wasm-bytes.ts.

import { spawnSync } from "node:child_process";
import { mkdirSync, copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = dirname(here);
const crateDir = join(repoRoot, "crates", "zstd-decoder");
const pkgDir = join(crateDir, "pkg");
const outDir = join(repoRoot, "src", "zstd-wasm");

const env = {
  ...process.env,
  CC: process.env.CC ?? "clang",
  AR: process.env.AR ?? "llvm-ar",
};

function run(cmd, args, opts = {}) {
  process.stderr.write(`[build-wasm] ${cmd} ${args.join(" ")}\n`);
  const res = spawnSync(cmd, args, { stdio: "inherit", env, ...opts });
  if (res.status !== 0) {
    throw new Error(`${cmd} exited with status ${res.status}`);
  }
}

function findWasmOpt() {
  // wasm-pack downloads wasm-opt under ~/.cache/.wasm-pack/. Use
  // that copy if a system one isn't on PATH — saves the user from
  // installing binaryen separately.
  const which = spawnSync("which", ["wasm-opt"]);
  if (which.status === 0) return which.stdout.toString().trim();
  const cache = join(
    process.env.HOME ?? "",
    ".cache",
    ".wasm-pack",
  );
  const cached = spawnSync("find", [cache, "-name", "wasm-opt", "-type", "f"]);
  const found = cached.stdout.toString().trim().split("\n")[0];
  if (found) return found;
  throw new Error(
    "wasm-opt not found. Either run a wasm-pack build first (it caches one), or install binaryen.",
  );
}

run("wasm-pack", ["build", "--release", "--target", "web"], { cwd: crateDir });

const rawWasm = join(pkgDir, "ctopo_zstd_decoder_bg.wasm");
const optWasm = join(pkgDir, "ctopo_zstd_decoder_bg.opt.wasm");
const wasmOpt = findWasmOpt();
run(wasmOpt, [
  "--enable-bulk-memory",
  "--enable-mutable-globals",
  "--enable-sign-ext",
  "-Oz",
  rawWasm,
  "-o",
  optWasm,
]);

mkdirSync(outDir, { recursive: true });

// Copy the wasm-bindgen-generated loader + types unmodified. We
// load via __wbg_init(bytes), which is async-safe even for large
// modules (browsers reject sync WebAssembly.Module compilation
// >4 KiB on the main thread).
copyFileSync(
  join(pkgDir, "ctopo_zstd_decoder.js"),
  join(outDir, "ctopo_zstd_decoder.js"),
);
copyFileSync(
  join(pkgDir, "ctopo_zstd_decoder.d.ts"),
  join(outDir, "ctopo_zstd_decoder.d.ts"),
);

const wasmBytes = readFileSync(optWasm);
const b64 = wasmBytes.toString("base64");
const optSize = wasmBytes.byteLength;
process.stderr.write(
  `[build-wasm] wasm: ${optSize} bytes (${(optSize / 1024).toFixed(1)} KiB), ` +
    `base64: ${b64.length} chars\n`,
);

const tsHeader =
  `// SPDX-License-Identifier: Apache-2.0\n` +
  `// © 2026 Michael Maurizi Jr.\n` +
  `//\n` +
  `// Auto-generated by scripts/build-wasm.mjs. Do not edit by hand.\n` +
  `// Source: crates/zstd-decoder. Re-build via \`npm run build:wasm\`.\n` +
  `//\n` +
  `// ${optSize} bytes raw wasm, base64-inlined so consumers don't need\n` +
  `// fetch + a separate .wasm asset.\n\n`;
const tsBody = `export const wasmBase64 = "${b64}";\n`;
writeFileSync(join(outDir, "wasm-bytes.ts"), tsHeader + tsBody);

process.stderr.write(`[build-wasm] wrote ${outDir}/{ctopo_zstd_decoder.js, .d.ts, wasm-bytes.ts}\n`);
